# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"

sphinx:
  configuration: doc/source/conf.py

conda:
  environment: doc/environment.yaml

python:
  install:
    - method: pip
      path: .
