name: dtoolkit
channels:
  - conda-forge
dependencies:
  # required
  - pandas >= 1.3.4
  # optional
  - scikit-learn >= 1.1
  - geopandas >= 0.9.0
  - pygeos >= 0.11.1
  - geopy
  - jenkspy
  - topojson

  - pip
  - pip:
      - my-data-toolkit

      # optional
      - simplification
