name: dtoolkit-dev
channels:
  - conda-forge
dependencies:
  - python >= 3.8

  # required
  - pandas >= 1.5.1
  # optional
  - scikit-learn >= 1.1
  - packaging
  - geopandas >= 0.10.0
  # TODO: delete pygeos after shapely 2.x released
  - pygeos
  - geopy
  - jenkspy
  - topojson
  - joblib

  # testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov
  # doctest testing
  - pytest-doctestplus

  # styling
  - black
  - pre-commit

  # doc
  - sphinx
  - pydata-sphinx-theme
  - myst-parser
  - numpydoc
  - ipython
  # jupyter
  - nbsphinx
  - ipykernel
  - pip
  - pip:
      # doc
      - sphinx-toggleprompt
