name: dtoolkit
channels:
  - conda-forge
dependencies:
  # required
  - pandas >= 2.0.3
  # optional
  - scikit-learn >= 1.4
  - packaging
  - geopandas >= 1.1.0
  - geopy
  - jenkspy
  - topojson
  - h3-py
  - joblib
  - rapidfuzz

  - pip
  - pip:
      - my-data-toolkit
