name: dtoolkit
channels:
  - conda-forge
dependencies:
  # required
  - pandas >= 1.3.4
  # optional
  - scikit-learn >= 1.1
  - packaging
  - geopandas >= 0.10.0
  - pygeos
  - geopy
  - jenkspy
  - topojson
  - joblib

  - pip
  - pip:
      - my-data-toolkit

      # optional
      - simplification
