name: dtoolkit-dev
channels:
  - conda-forge
dependencies:
  - python >= 3.10

  # required
  - pandas >= 2.0.3
  # optional
  - scikit-learn >= 1.4
  - packaging
  - geopandas >= 1.1.0
  - geopy
  - jenkspy
  - topojson
  - h3-py >= 4.1.2
  - joblib
  - rapidfuzz

  # testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov
  # doctest testing
  - pytest-doctestplus

  # styling
  - black
  - pre-commit

  # doc
  - sphinx
  - pydata-sphinx-theme
  - myst-parser
  - numpydoc
  - ipython
  # jupyter
  - nbsphinx
  - ipykernel
  - pip
  - pip:
      # doc
      - sphinx-toggleprompt
