name: dtoolkit
channels:
  - conda-forge
dependencies:
  # required
  - pandas >= 1.5.1
  # optional
  - scikit-learn >= 1.1
  - packaging
  - geopandas >= 0.10.0
  # TODO: delete pygeos after shapely 2.x released
  - pygeos
  - geopy
  - jenkspy
  - topojson
  - joblib
  - thefuzz

  - pip
  - pip:
      - my-data-toolkit
