name: test
channels:
  - conda-forge
dependencies:
  - cython
  - numpy
  # geo
  - geos
  - fiona
  - pyproj
  - shapely
  # testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov
  # dev versions of packages
  - pip
  - pip:
    - git+https://github.com/pydata/pandas@master
    - git+https://github.com/scikit-learn/scikit-learn@main
    - git+https://github.com/geopandas/geopandas@main
    - git+https://github.com/pygeos/pygeos@master
