name: test
channels:
  - conda-forge
dependencies:
  - cython
  - numpy
  # geo
  - geos
  - fiona
  - pyproj
  - shapely
  # testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov
  # dev versions of packages
  - pip
  - pip:
    - --pre --extra-index https://pypi.anaconda.org/scipy-wheels-nightly/simple pandas
    - git+https://github.com/scikit-learn/scikit-learn
    - git+https://github.com/geopandas/geopandas
    - git+https://github.com/pygeos/pygeos
