name: test
channels:
  - conda-forge
dependencies:
  - cython
  # the dependencies of dependencies
  # computing
  - numpy
  - scipy
  - joblib
  - threadpoolctl
  # time
  - python-dateutil
  - pytz
  # geo
  - geos
  - fiona
  - pyproj
  - shapely
  - geopy
  - topojson
  # testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov
  # dev versions of packages
  - pip
  - pip:
    # required
    - git+https://github.com/pydata/pandas
    # optional
    - git+https://github.com/scikit-learn/scikit-learn
    - git+https://github.com/geopandas/geopandas
    - git+https://github.com/pygeos/pygeos
