name: dtoolkit_doc
channels:
  - conda-forge
dependencies:
  - python
  # package dependencies
  - pandas
  - scikit-learn
  - geopandas
  - pygeos
  # doc dependencies
  - sphinx
  - pydata-sphinx-theme
  - myst-parser
  - numpydoc
  - ipython
  - nbsphinx
  - pip
  - pip:
      - sphinx-toggleprompt
