name: dtoolkit-doc
channels:
  - conda-forge
dependencies:
  - python>=3.8
  # package dependencies
  - pandas
  - scikit-learn
  - geopandas
  - pygeos

  # doc dependencies
  - sphinx
  - pydata-sphinx-theme=0.9.0
  - myst-parser
  - numpydoc
  - ipython

  # jupyter
  - nbsphinx
  - ipykernel
  - pip
  - pip:
      - sphinx-toggleprompt
