name: dtoolkit_doc
channels:
  - conda-forge
dependencies:
  - python>=3.7
  # package dependencies
  - numpy
  - pandas
  - scikit-learn
  - geopandas
  - pygeos
  # doc dependencies
  - sphinx
  - pydata-sphinx-theme
  - myst-parser
  - numpydoc
  - ipython
  # jupyter
  - nbsphinx
  - ipykernel
  - pip
  - pip:
      - sphinx-toggleprompt
