name: dtoolkit_doc
channels:
  - conda-forge
dependencies:
  - python
  # package dependencies
  - pandas
  - geopandas
  - scikit-learn
  - more-itertools
  # doc dependencies
  - sphinx
  - pydata-sphinx-theme
  - myst-parser
  - numpydoc
  - pip
  - pip:
      - sphinx-toggleprompt
