name: branch

on:
  push:
    branches: [main]

jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        id: branch
        env:
          GITHUB_TOKEN: ${{ secrets.PERSON_GITHUB_TOKEN }}
          PR_FILTER: "auto_merge"
          PR_READY_STATE: "ready_for_review"

      - run: echo 'Merge conflicts found!'
        if: ${{ steps.branch.outputs.conflicted }}
