name: cancel

on: [push]

jobs:
  cancel:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          workflow_id: |
            .github/workflows/tests.yml,
            .github/workflows/nightly-tests.yml,
            .github/workflows/sdist.yml
            .github/workflows/sphinx.yml,
            .github/workflows/codeql-analysis.yml,
