name: cancel

on: [push]

jobs:
  cancel:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          workflow_id: |
            .github/workflows/codeql-analysis.yaml,
            .github/workflows/test.yaml,
            .github/workflows/versioneer.yaml,
