name: cancel

on:
  push:
    branches: ["!main"]

jobs:
  cancel:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: |
            .github/workflows/tests.yml,
            .github/workflows/nightly-tests.yml,
            .github/workflows/sdist.yml
            .github/workflows/sphinx.yml,
            .github/workflows/codeql-analysis.yml,
