name: CI


on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run .travis.yml
        uses: ktomk/run-travis-yml@v1.7.0
