name: nightly tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  nightly-tests:
    name: ${{ matrix.os }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest]
        dev: [true]
        env:
          - ci/envs/37-dev.yaml
          - ci/envs/38-dev.yaml
          - ci/envs/39-dev.yaml

    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda and Install Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ${{ matrix.env }}

      - name: Check and Log Environment
        run: make info

      - name: Test with Pytest
        run: make test

      - name: Code Coverage
        uses: codecov/codecov-action@v1
