name: nightly tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  skip-check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip-check.outputs.should-skip }}
    steps:
      - uses: fkirc/skip-duplicate-actions@v3.4.1
        id: skip-check
        with:
          paths_ignore: '["doc/**"]'

  nightly-tests:
    needs: skip-check
    if: ${{ needs.skip-check.outputs.should-skip != 'true' }}
    name: ${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dev: [true]
        python-version: ["3.8", "3.9", "3.10"]
        env:
          - ci/env/dev.yaml

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ${{ matrix.env }}
          python-version: ${{ matrix.python-version }}
          use-mamba: true

      - name: Check and Log Environment
        run: make info

      - name: Test with Pytest
        run: make test

      - uses: codecov/codecov-action@v2.1.0
