name: nightly tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  nightly-tests:
    name: ${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dev: [true]
        python-version: ["3.8", "3.9"]
        env:
          - ci/envs/dev.yaml

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Conda and Install Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ${{ matrix.env }}
          python-version: ${{ matrix.python-version }}

      - name: Check and Log Environment
        run: make info

      - name: Test with Pytest
        run: make test

      - name: Code Coverage
        uses: codecov/codecov-action@v1
