name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Build a Binary Wheel and a Source Tarball
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          make dist

      - name: Get Source Tarball Name
        id: tar
        run: |
          export type=tar
          export file=$(ls dist/ | grep ${type})
          echo "::set-output name=file::${file}"

      - name: Get Binary Wheel Name
        id: whl
        run: |
          export type=whl
          export file=$(ls dist/ | grep ${type})
          echo "::set-output name=file::${file}"

    outputs:
      var: ${{ steps.tar.outputs.file }}
      whl: ${{ steps.whl.outputs.file }}

  github:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Upload Release Asset to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/${{ needs.build.outputs.var }}
            dist/${{ needs.build.outputs.whl }}
