name: sdist

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths-ignore:
      - "doc/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Build sdist
        run: |
          pip list
          make dist

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dtoolkit-sdist
          python-version: "${{ matrix.python-version }}"

      - name: Install from sdist
        run: |
          pip list
          python -m pip install dist/*.gz

      - name: Import dtoolkit
        run: |
          cd ..
          make info
