name: sdist

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  skip-check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip-check.outputs.should-skip }}
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths_ignore: '["doc/**"]'

  sdist:
    needs: skip-check
    if: ${{ needs.skip-check.outputs.should-skip != 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Build sdist
        run: |
          pip list
          make dist

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dtoolkit-sdist
          python-version: ${{ matrix.python-version }}

      - name: Install from sdist
        run: |
          pip list
          python -m pip install dist/*.gz

      - name: Import dtoolkit
        run: make info

      - name: Publish to TestPyPI
        if: ${{ github.event_name == 'push' }}
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
          skip_existing: true
