name: sphinx

on:
  pull_request:
    branches: [main]

jobs:
  skip-check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip-check.outputs.should-skip }}
    steps:
      - uses: fkirc/skip-duplicate-actions@v3.4.1
        id: skip-check
        with:
          paths_ignore: '["test/**", "ci/**"]'

  sphinx:
    needs: skip-check
    if: ${{ needs.skip-check.outputs.should-skip != 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - uses: actions/setup-python@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dtoolkit_doc
          environment-file: doc/environment.yml

      - name: Install Dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install DToolKit
        run: python setup.py install

      - name: Check and Log Environment
        run: make info

      - name: Build Sphinx HTML
        run: make html
