name: sphinx

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sphinx:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dtoolkit_doc
          environment-file: doc/environment.yml
          add-pip-as-python-dependency: true

      - name: Install DToolKit
        run: python setup.py install

      - name: Check and Log Environment
        run: make info

      - name: Build Sphinx HTML
        run: make html
