name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        dev: [false]
        python-version:
          - "3.14"
        env: [ci/env/latest.yaml]
        include:
          - env: ci/env/310-minimal.yaml
            os: ubuntu-latest
            dev: false
            python-version: "3.10"
          - env: ci/env/311-minimal.yaml
            os: ubuntu-latest
            dev: false
            python-version: "3.11"
          - env: ci/env/312-minimal.yaml
            os: ubuntu-latest
            dev: false
            python-version: "3.12"
          - env: ci/env/313-minimal.yaml
            os: ubuntu-latest
            dev: false
            python-version: "3.13"
          - env: ci/env/latest-base.yaml
            os: ubuntu-latest
            dev: false
            python-version: "3.13"
          - env: ci/env/dev.yaml
            os: ubuntu-latest
            dev: false
            python-version: "3.13"

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - uses: mamba-org/setup-micromamba@v2.0.7
        with:
          environment-file: ${{ matrix.env }}
          create-args: python=${{ matrix.python-version }}

      - name: Check and Log Environment
        run: make info

      - name: Test Docstrings
        if: ${{ contains(matrix.env, 'latest.yaml') && contains(matrix.os, 'ubuntu') && matrix.python-version == '3.13' }}
        run: make doctest

      - name: Test with Pytest
        run: make test

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
