name: Tests Pipeline

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  Test:
    needs: Linting
    name: ${{ matrix.os }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dev: [false]
        env:
          - ci/envs/37.yaml
          - ci/envs/38.yaml
    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false

      - name: Install Env
        shell: bash
        run: conda env create -f ${{ matrix.env }}

      - name: Check and Log Environment
        shell: bash
        run: |
          source activate test
          python -V
          conda info
          conda list

      - name: Test with Pytest
        shell: bash
        run: |
          source activate test
          coverage run -m pytest

      - name: Code Coverage
        uses: codecov/codecov-action@v1
