name: Tests Pipeline

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  Test:
    needs: Linting
    name: Test at ${{ matrix.os }} with Py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        dev: [false]
        python-version: [3.7, 3.8, 3.9]
        include:
          - os: macos-latest
            dev: false
          - os: windows-latest
            dev: false
          - os: ubuntu-latest
            dev: true
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Install dtoolkit
        run: |
          python setup.py check
          python setup.py install

      - name: Test with Pytest
        run: |
          coverage run -m pytest

      - name: Code Coverage
        uses: codecov/codecov-action@v1
