name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: ${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dev: [false]
        python-version: ["3.7", "3.8", "3.9"]
        env:
          - ci/envs/latest.yaml
        include:
          - env: ci/envs/37-minimal.yaml
            os: ubuntu-latest
            dev: false
            python-version: "3.7"
          - env: ci/envs/38-minimal.yaml
            os: ubuntu-latest
            dev: false
            python-version: "3.8"
          - env: ci/envs/39-minimal.yaml
            os: ubuntu-latest
            dev: false
            python-version: "3.9"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Conda and Install Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ${{ matrix.env }}
          python-version: ${{ matrix.python-version }}

      - name: Check and Log Environment
        run: make info

      - name: Test with Pytest
        run: make test

      - name: Test Docstrings
        if: contains(matrix.env, 'latest') && contains(matrix.os, 'ubuntu')
        run: make doctest

      - name: Code Coverage
        uses: codecov/codecov-action@v1
