name: Tests Pipeline

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  Test:
    needs: Linting
    name: Test at ${{ matrix.os }} with Py${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        dev: [false]
        env:
          - ci/envs/37.yaml
          - ci/envs/38.yaml
          - ci/envs/39.yaml
        include:
          - env: ci/envs/37.yaml
            os: windows-latest
          - env: ci/envs/38.yaml
            os: windows-latest
          - env: ci/envs/39.yaml
            os: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false

      - name: Install Env
        shell: bash
        run: conda env create -f ${{ matrix.env }}

      - name: Install dtoolkit
        shell: bash
        run: |
          python setup.py check
          python setup.py install

      - name: Test with Pytest
        shell: bash
        run: coverage run -m pytest

      - name: Code Coverage
        uses: codecov/codecov-action@v1
