name: Tests

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  Test:
    needs: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run .travis.yml
        uses: ktomk/run-travis-yml@v1.7.0

  Codecov:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - uses: codecov/codecov-action@v1
