name: workflow-run

on:
  workflow_dispatch:
    inputs:
      days:
        description: "Number of days."
        required: true
        default: "30"
      minimum_runs:
        description: "The minimum runs to keep for each workflow."
        required: true
        default: "7"
      delete_workflow_pattern:
        description: "The name or filename of the workflow. if not set then it will target all workflows."
        required: false
      delete_workflow_by_state_pattern:
        description: "Remove workflow runs by state."
        required: false
        default: all
        type: choice
        options:
          - all
          - active
          - deleted
          - disabled_fork
          - disabled_inactivity
          - disabled_manually
      dry_run:
        description: "Only log actions, do not perform any delete operations."
        required: false

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}
          delete_workflow_pattern: ${{ github.event.inputs.delete_workflow_pattern }}
          delete_workflow_by_state_pattern: ${{ github.event.inputs.delete_workflow_by_state_pattern }}
          dry_run: ${{ github.event.inputs.dry_run }}
